version: '3.8'

services:
  lead_auto_assignment_automation:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    command: python3 server.py